name: CI/CD pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [  master ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "GitHub Actions"

      - name: Create artifact file
        run: |
          echo "Run ID: $GITHUB_RUN_ID" > run-info.txt
          date >> run-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-info
          path: run-info.txt
